[package]
name = "bitfield-impl"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.38", features = ["full"] }
proc-macro2 = { version = "1.0.69" }
quote = { version = "1.0.33" }
